# This workflow will build bench routes
# on the Linux platform.
name: continuous-integeration/linux

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check format and lint
        run: |
          diff -u <(echo -n) <(gofmt -d ./src ./tsdb)
          echo "format all good"
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1
          $(go env GOPATH)/bin/golangci-lint run
          echo "lint all good"
      - name: Build
        run: make build
      - name: Unit test
        run: make test
